server {
    listen 80;

    location / {
        root /usr/share/nginx/html; # This is where frontends build gets copied to.
        index index.html; #The default file server should serve.
        try_files $uri $uri/ /index.html; # Handles client side routing, not sure if i need it yet but currently its here.
    }
    location /api/ {
        proxy_pass http://backend:8888/;  #Proxy requests to backend service.
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        # this proxys API calls to backend service that runs on different port making it a different origin and would trigger same-origin policy.
    }
}